spring:
  redis:
      host: 10.0.49.58
      port: 6379
  datasource:
    url: jdbc:mysql://10.0.49.59:3306/ems_process?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    password: emsprocess
    username: emsprocess
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20
    loginPassword : '123456'
    loginUsername : ''
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      location: /home/appuser/appServer/temp
    
server:
  port: 7011
  basedir: /home/appuser/appServer/temp


eureka:
  client:
    service-url:
      defaultZone: http://10.0.49.63:7061/eureka
  instance:
    prefer-ip-address: true
    status-page-url-path: /swagger-ui.html
    
mybatis:
  mapper-locations: classpath:xml/*.xml


threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 200
  keep-alive-seconds: 300
 
